name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      INPUT_WORKING_DIR:
        description: 'Project to build and publish'
        required: true
        type: choice
        default: "none"
        options: 
          - "Infrastructure/Pull"

jobs:
  nughets-handler:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Versioning
          id: versioning
          shell: bash
          run: |
            printenv
